name = "Newb Classic"
version = [0, 16, 53]
min_supported_mc_version = [1, 26, 30]
description = '''
§c%w
§7- An enchanced vanilla shader for Minecraft!
%v
§3https://newb-shader.devendrn.com/
''' # %w = patch warning, %v = version
authors = ["devendrn"]
url = "https://newb-shader.devendrn.com/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["RenderChunk", "Actor", "ActorGlint", "ActorBanner", "Clouds"]

[info] 
copyright = '''
''' # %a = authors
credits = '''
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
