name = "classic graphics"
version = [0, 0, 0]
min_supported_mc_version = [1, 26, 40]
description = '''
'''
authors = ["chromehaert"]
url = ""
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2"
materials = ["RenderChunk", "Actor", "ActorBanner", "ActorGlint", "ItemInHandColor", "ItemInHandColorGlint", "ItemInHandTextured"]

[info] 
copyright = '''
'''
credits = '''
'''

[[subpack]]
define = "chromehaert"
materials = []
description = '''
chromehaert
'''
